name: areswave-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - scipy
  - pandas
  - matplotlib
  - obspy
  - corner
  - pyswarms
  - mpi4py
  - tqdm
  - compilers
  - openmpi
  - pip
